version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-app
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: Content/hello.py
      timeout: 180
  ValidateService:
    - location: Content/hellotest.py
      timeout: 3600
      runas: ec2-user
